# Nombre de la aplicaci�n
spring.application.name=Integradora5A_SIGRAD

# --- CONFIGURACI�N DE ORACLE CLOUD ---
# Aseg�rate de que la carpeta 'wallet' est� en src/main/resources/
# Reemplaza C:/Tu/Ruta/Real por la ubicación real en tu disco
spring.datasource.url=jdbc:oracle:thin:@lxe176e6rrw0nxz6_high?TNS_ADMIN=Integradora5A_SIGRAD/src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=NicholasSIGRAD2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- CONFIGURACI�N DE JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 'update' crear� las tablas autom�ticamente en Oracle al iniciar el servidor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SEGURIDAD DE RED (WALLET) ---
# Coincidencia de nombre de servidor SSL para mayor seguridad [cite: 21, 31]
oracle.net.ssl_server_dn_match=yes