spring.datasource.url=jdbc:oracle:thin:@lxe176e6rrw0nxz6_high?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=NicholasSIGRAD2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update