# ==========================================
# CONEXIÓN ORACLE (COMENTADA PARA PRUEBAS)
# ==========================================
 spring.datasource.url=jdbc:oracle:thin:@lxe176e6rrw0nxz6_high?TNS_ADMIN=src/main/resources/wallet
 spring.datasource.username=ADMIN
 spring.datasource.password=NicholasSIGRAD2026
 spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
 spring.jpa.hibernate.ddl-auto=update

# ==========================================
# CONEXIÓN H2 (EN MEMORIA)
# ==========================================
#spring.datasource.url=jdbc:h2:mem:sigrad_db;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## Hibernate creará las tablas de cero cada vez que corras el proyecto
#spring.jpa.hibernate.ddl-auto=create-drop
#
## Habilitar la consola web de H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console/

# ==========================================
# MAIL (SMTP) - CONFIGURA ESTO PARA ENVÍOS REALES
# ==========================================
# Ejemplo genérico (ajústalo a tu proveedor):
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=20243ds051@utez.edu.mx
spring.mail.password=wjergbnrspgxdnne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true